Updates to translation map
comvex-jp/mediasms-go pull request #6
Opened 2020-10-20 07:15 UTC by CJButton

## Description:

- Updates to the translation map. Now using integer strings e.g. "1" instead of actual words.
- Refactored the functions and extracted the request method.

## Added

- `makeRequest` is a private function that deals with actually doing a request

## Changed

- At the moment, this is returning errors as `error` type. It feels very anti-pattern to return them as strings. As type `error` they can be handled as any other error would be. e.g. 
```
res, err := client.Send(...)

if err != nil {
 // do something
}
```

We will still need to handle responses where the api failed in some fashion, e.g. `duplicated smsid` or something with a `StatusCode` that is not `200`.

- `Send` and `GetStatus` mostly deal with handling results now.

- Updates to the translation map

## References:

https://github.com/comvex-jp/mediasms-go/issues/5

2020-10-20 07:35 UTC, rdehaas-comvex requested changes

2020-10-20 07:35 UTC, rdehaas-comvex commented on translations/translations.go
> +	"43": "Error status for Rakuten",
For all these error messages that are duplicated, can we add the details from the original Japanese status?
You can ask Yuka to translate these.

For example:
`"43": "Rakuten out of reception zone"`

2020-10-27 06:18 UTC, anderson-comvex requested changes

2020-10-27 06:18 UTC, anderson-comvex commented on translations/translations.go
> +	"25": "CSV file with SMS was paused",
Can we add the 26 for replies (inbound sms)

2020-10-27 06:33 UTC, rdehaas-comvex approved these changes

2020-10-29 07:12 UTC, anderson-comvex approved these changes

2020-11-02 04:56 UTC, merged