Adds URLReplacement functionality
comvex-jp/mediasms-go pull request #9
Opened 2020-11-13 07:07 UTC by CJButton

## Description:

Replacing URLs in message body has been moved from `sms-api` to this library. 

Usage:
```
messageBody := "http://google.com test message http://stackoverflow.com"
allURLs := []string{"http://google.com", "http://stackoverflow.com"}

request.SMSText = mediasms.ReplaceMessageBodyURLs(contactMessage.Body, allURLs)
```

Result
`"{URL} test message {URL2}"`

## Added

- URL Replacement function
- test

## References:

https://comvex.myjetbrains.com/youtrack/agiles/107-0/108-196?issue=DGM2-4103

2020-11-13 07:25 UTC, rdehaas-comvex approved these changes

2020-11-13 07:26 UTC, rdehaas-comvex requested changes

2020-11-13 07:26 UTC, rdehaas-comvex commented on mediasms.go
> +	return messageBody
Can you add an empty line before the return

2020-11-17 06:51 UTC, rdehaas-comvex approved these changes

2020-11-17 06:51 UTC, anderson-comvex approved these changes

2020-11-17 06:52 UTC, cliff-comvex approved these changes

2020-11-17 06:57 UTC, merged